<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.Domain\Core.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="HCM.Domain">
      <HintPath>..\..\..\..\HCM\src\Services\HCM\HCM.Domain\bin\Debug\net8.0\HCM.Domain.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
