<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="FluentValidation" Version="11.9.0" />
		<PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
		<PackageReference Include="MediatR" Version="12.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2" />
		<PackageReference Include="Dapper" Version="2.1.35" />
		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.4" />
		<PackageReference Include="LinqKit" Version="1.2.5" />

	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core.Domain\Core.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="DTOs\CostCenter\" />
    <Folder Include="Features\Users\Commands\CreateUserPermission\" />
    <Folder Include="Features\Users\Queries\Get\" />
    <Folder Include="Response\" />
  </ItemGroup>

</Project>
