// <auto-generated />
using System;
using Core.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117181202_approvalprocess")]
    partial class approvalprocess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Core")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("BNKBRID", "dbo");

            modelBuilder.HasSequence<int>("BNKID", "dbo");

            modelBuilder.HasSequence<int>("CNTRYID", "dbo");

            modelBuilder.HasSequence<int>("COMID", "dbo");

            modelBuilder.HasSequence<int>("CURNCYID", "dbo");

            modelBuilder.HasSequence<int>("DEPTID", "dbo");

            modelBuilder.HasSequence<int>("GrpComID", "dbo");

            modelBuilder.HasSequence<int>("GrpID", "dbo");

            modelBuilder.HasSequence<int>("GrpMnuID", "dbo");

            modelBuilder.HasSequence<int>("MODID", "dbo");

            modelBuilder.HasSequence<int>("RTID", "dbo");

            modelBuilder.HasSequence<int>("SECTID", "dbo");

            modelBuilder.HasSequence<int>("TheNumberID", "dbo");

            modelBuilder.HasSequence<int>("UserComID", "dbo");

            modelBuilder.HasSequence<int>("UserMnuPermsID", "dbo");

            modelBuilder.Entity("Core.Domain.Entities.AppModule", b =>
                {
                    b.Property<int>("ModSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModID")
                        .HasColumnType("int");

                    b.Property<string>("ModName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ModSerialID");

                    b.ToTable("Module", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.ApprovalActionHistory", b =>
                {
                    b.Property<long>("ApprovalActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApprovalActionID"));

                    b.Property<byte>("Action")
                        .HasColumnType("tinyint");

                    b.Property<int>("ActionByUserSerialID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApprovalRequestID")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalStepID")
                        .HasColumnType("int");

                    b.Property<byte>("NewState")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PreviousState")
                        .HasColumnType("tinyint");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ApprovalActionID");

                    b.ToTable("ApprovalActionHistory", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Property<int>("ApprovalRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalRequestID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ApprovalWorkflowID")
                        .HasColumnType("int");

                    b.Property<int>("ComSerialID")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("CurrentState")
                        .HasColumnType("tinyint");

                    b.Property<int>("CurrentStepOrder")
                        .HasColumnType("int");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<int>("EntityTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlantID")
                        .HasColumnType("int");

                    b.Property<int>("RequestedByUserSerialID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ApprovalRequestID");

                    b.HasIndex("ApprovalWorkflowID");

                    b.ToTable("ApprovalRequest", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.ApprovalRequestStep", b =>
                {
                    b.Property<int>("ApprovalRequestStepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalRequestStepID"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ApprovalRequestID")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalStepID")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedUserSerialID")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<byte>("StepStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("ApprovalRequestStepID");

                    b.HasIndex("ApprovalRequestID");

                    b.HasIndex("ApprovalStepID");

                    b.ToTable("ApprovalRequestStep", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.ApprovalStep", b =>
                {
                    b.Property<int>("ApprovalStepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalStepID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ApprovalRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ApprovalWorkflowID")
                        .HasColumnType("int");

                    b.Property<bool>("CanReject")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinalStep")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlantID")
                        .HasColumnType("int");

                    b.Property<string>("StepCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("ApprovalStepID");

                    b.HasIndex("ApprovalWorkflowID");

                    b.ToTable("ApprovalStep", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Property<int>("ApprovalWorkflowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalWorkflowID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ComSerialID")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkflowCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ApprovalWorkflowID");

                    b.HasIndex("EntityTypeID");

                    b.ToTable("ApprovalWorkflow", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.City", b =>
                {
                    b.Property<int>("CitySerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitySerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CntrySerialID")
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Flag")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Native")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateSerialID")
                        .HasColumnType("int");

                    b.Property<string>("Timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CitySerialID");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 1");

                    b.ToTable("City", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.Company", b =>
                {
                    b.Property<int>("ComSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Address3")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("BR")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("BR#");

                    b.Property<int>("CntrySerialID")
                        .HasColumnType("int");

                    b.Property<string>("ComCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("ComID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("SELECT NEXT VALUE FOR dbo.COMID");

                    b.Property<string>("ComName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("CompanyName");

                    b.Property<string>("CompanyLogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Fax")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile1")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Mobile2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NBT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegAdrs1")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("RegAdrs2")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("RegAdrs3")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("SOPayrollPeriodEndDay")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("SOPayrollPeriodStartDay")
                        .HasColumnType("tinyint");

                    b.Property<string>("SVAT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SmallComLogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telephone1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Telephone2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Telephone3")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VAT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte?>("WBPayrollPeriodEndDay")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("WBPayrollPeriodStartDay")
                        .HasColumnType("tinyint");

                    b.Property<string>("WebSite")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ComSerialID");

                    b.HasIndex("CntrySerialID");

                    b.HasIndex("ComSerialID");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 1");

                    b.ToTable("Company", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CntrySerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CntrySerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("AreaSqKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CntryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("CntryID")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmojiU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Flag")
                        .HasColumnType("bit");

                    b.Property<string>("FlagUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Native")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumericCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCodeFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCodeRegex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionSerialID")
                        .HasColumnType("int");

                    b.Property<string>("Subregion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubregionSerialID")
                        .HasColumnType("int");

                    b.Property<string>("ThreeLetterIsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Timezones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tld")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoLetterIsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("WikiDataId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CntrySerialID");

                    b.HasIndex("CntryID")
                        .IsUnique();

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 1");

                    b.ToTable("Country", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("CurSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("CurID")
                        .HasColumnType("int");

                    b.Property<string>("CurNmame")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CurSerialID");

                    b.ToTable("Currency", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.DelRecord", b =>
                {
                    b.Property<int>("DelRecSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DelRecSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DocSerialID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DocTable")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DelRecSerialID");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 1");

                    b.ToTable("DelRecord", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.DocType", b =>
                {
                    b.Property<short>("DocTypeSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("DocTypeSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModSerialID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DocTypeSerialID");

                    b.HasIndex("ModSerialID");

                    b.ToTable("DocType", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.DocUpload", b =>
                {
                    b.Property<int>("DocUploadSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocUploadSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocDescription")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<short>("DocTypeSerialID")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModSerialID")
                        .HasColumnType("int")
                        .HasColumnName("ModuleSerialID");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DocUploadSerialID");

                    b.HasIndex("DocTypeSerialID");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 1");

                    b.HasIndex("ModSerialID");

                    b.ToTable("DocUpload", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.EntityType", b =>
                {
                    b.Property<int>("EntityTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityTypeID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EntityTypeID");

                    b.ToTable("EntityType", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.FilePaths", b =>
                {
                    b.Property<short>("FilePathSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("FilePathSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("DocTypeSerialID")
                        .HasColumnType("smallint");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FilePathSerialID");

                    b.HasIndex("DocTypeSerialID");

                    b.ToTable("FilePaths", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.Group", b =>
                {
                    b.Property<int>("GrpSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrpSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GropName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("GrpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("SELECT NEXT VALUE FOR dbo.GrpID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GrpSerialID");

                    b.HasIndex("GrpID")
                        .IsUnique();

                    b.ToTable("Group", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.GroupMenu", b =>
                {
                    b.Property<int>("GrpMnuSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrpMnuSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrpMnuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("SELECT NEXT VALUE FOR dbo.GrpMnuID");

                    b.Property<int>("GrpSerialID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MnuID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GrpMnuSerialID");

                    b.HasIndex("GrpMnuID")
                        .IsUnique();

                    b.HasIndex("GrpSerialID");

                    b.HasIndex("MnuID");

                    b.ToTable("GroupMenu", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.InvalidateToken", b =>
                {
                    b.Property<int>("InvdTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvdTokenID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InvdTokenID");

                    b.ToTable("InvalidateToken", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.LoginLog", b =>
                {
                    b.Property<long>("LoginLogSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LoginLogSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemLogout")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTimeout")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LoginDateTime")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpire")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserSerialID")
                        .HasColumnType("int");

                    b.HasKey("LoginLogSerialID");

                    b.HasIndex("UserSerialID");

                    b.ToTable("LoginLog", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("MnuSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MnuSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBtnInc")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRptInc")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShown")
                        .HasColumnType("bit")
                        .HasColumnOrder(8);

                    b.Property<int>("MnuID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<byte>("MnuLevel")
                        .HasColumnType("tinyint")
                        .HasColumnOrder(3);

                    b.Property<string>("MnuMTBR")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MnuName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(5);

                    b.Property<decimal>("MnuPosition")
                        .HasColumnType("decimal(8, 6)")
                        .HasColumnOrder(4);

                    b.Property<string>("MnuText")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnOrder(6);

                    b.Property<int?>("ModSerialID")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)")
                        .HasColumnOrder(7);

                    b.Property<int?>("ParentID")
                        .HasColumnType("int")
                        .HasColumnOrder(9);

                    b.HasKey("MnuSerialID");

                    b.HasIndex("MnuID")
                        .IsUnique();

                    b.HasIndex("MnuSerialID")
                        .IsUnique();

                    b.HasIndex("ModSerialID");

                    b.ToTable("Menu", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.Reason", b =>
                {
                    b.Property<int>("ReasonSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModSerialID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReasonSerialID");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 1");

                    b.HasIndex("ModSerialID");

                    b.HasIndex("ReasonSerialID");

                    b.ToTable("Reason", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RTSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RTSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("SELECT NEXT VALUE FOR dbo.RTID");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserSerialID")
                        .HasColumnType("int");

                    b.HasKey("RTSerialID");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 1");

                    b.HasIndex("RTSerialID")
                        .IsUnique();

                    b.HasIndex("UserSerialID");

                    b.ToTable("RefreshToken", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.Region", b =>
                {
                    b.Property<int>("RegionSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Flag")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiDataId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionSerialID");

                    b.ToTable("Region", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.Report", b =>
                {
                    b.Property<short>("ReportSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ReportSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataBaseName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("DataBaseSPName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DataSet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MnuID")
                        .HasColumnType("int");

                    b.Property<int>("ModSerialID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Orientation")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("ReportName");

                    b.Property<int?>("ReportTypeID")
                        .HasColumnType("int");

                    b.HasKey("ReportSerialID");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 1");

                    b.HasIndex("MnuID");

                    b.HasIndex("ModSerialID");

                    b.HasIndex("ReportName");

                    b.ToTable("Report", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.State", b =>
                {
                    b.Property<int>("StateSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CntrySerialID")
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FipsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Flag")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Native")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint");

                    b.Property<string>("ThreeLetterIsoCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoLetterIsoCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateSerialID");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 1");

                    b.ToTable("State", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.Subregion", b =>
                {
                    b.Property<int>("SubregionSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubregionSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Flag")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionSerialID")
                        .HasColumnType("int");

                    b.Property<string>("Translations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiDataId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubregionSerialID");

                    b.ToTable("Subregion", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.TheNumber", b =>
                {
                    b.Property<int>("TheNumberSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TheNumberSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("ComSerialID")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TheNumberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("SELECT NEXT VALUE FOR dbo.TheNumberID");

                    b.Property<string>("TheNumberName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("TheNumberSerialID");

                    b.ToTable("TheNumbers", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EESerialID")
                        .HasColumnType("bigint");

                    b.Property<int?>("GrpSerialID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLogOut")
                        .HasColumnType("bit");

                    b.Property<string>("LastIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LastSessionId")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LastToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswdHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(10);

                    b.Property<string>("PasswdSalt")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnOrder(9);

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserSerialID");

                    b.HasIndex("GrpSerialID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("User", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.UserCompany", b =>
                {
                    b.Property<int>("UserComSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserComSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ComSerialID")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserComID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("SELECT NEXT VALUE FOR dbo.UserComID");

                    b.Property<int>("UserSerialID")
                        .HasColumnType("int");

                    b.HasKey("UserComSerialID");

                    b.HasIndex("ComSerialID");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 1");

                    b.HasIndex("UserComID")
                        .IsUnique();

                    b.HasIndex("UserSerialID");

                    b.ToTable("UserCompany", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.UserMenuPermission", b =>
                {
                    b.Property<int>("UserMnuPermsSerialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserMnuPermsSerialID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrpSerialID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MnuID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserMnuPermsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("SELECT NEXT VALUE FOR dbo.UserMnuPermsID");

                    b.Property<int>("UserSerialID")
                        .HasColumnType("int");

                    b.HasKey("UserMnuPermsSerialID");

                    b.HasIndex("GrpSerialID");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 1");

                    b.HasIndex("MnuID");

                    b.HasIndex("UserMnuPermsID")
                        .IsUnique();

                    b.HasIndex("UserSerialID");

                    b.ToTable("UserMenuPermission", "Core");
                });

            modelBuilder.Entity("Core.Persistence.Audit.AuditTrail", b =>
                {
                    b.Property<long>("AudtTralID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AudtTralID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AuditData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LoginLogSerialID")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MnuSerialID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserSerialID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("AudtTralID");

                    b.ToTable("AuditTrail", "Core");
                });

            modelBuilder.Entity("Core.Domain.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("Core.Domain.Entities.ApprovalWorkflow", "ApprovalWorkflow")
                        .WithMany()
                        .HasForeignKey("ApprovalWorkflowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflow");
                });

            modelBuilder.Entity("Core.Domain.Entities.ApprovalRequestStep", b =>
                {
                    b.HasOne("Core.Domain.Entities.ApprovalRequest", "ApprovalRequest")
                        .WithMany("RequestSteps")
                        .HasForeignKey("ApprovalRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.ApprovalStep", "ApprovalStep")
                        .WithMany()
                        .HasForeignKey("ApprovalStepID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalRequest");

                    b.Navigation("ApprovalStep");
                });

            modelBuilder.Entity("Core.Domain.Entities.ApprovalStep", b =>
                {
                    b.HasOne("Core.Domain.Entities.ApprovalWorkflow", "ApprovalWorkflow")
                        .WithMany("ApprovalSteps")
                        .HasForeignKey("ApprovalWorkflowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflow");
                });

            modelBuilder.Entity("Core.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.HasOne("Core.Domain.Entities.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("Core.Domain.Entities.Company", b =>
                {
                    b.HasOne("Core.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CntrySerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Core.Domain.Entities.DocType", b =>
                {
                    b.HasOne("Core.Domain.Entities.AppModule", "Module")
                        .WithMany()
                        .HasForeignKey("ModSerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Core.Domain.Entities.DocUpload", b =>
                {
                    b.HasOne("Core.Domain.Entities.DocType", "DocType")
                        .WithMany()
                        .HasForeignKey("DocTypeSerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.AppModule", "Module")
                        .WithMany()
                        .HasForeignKey("ModSerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocType");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Core.Domain.Entities.FilePaths", b =>
                {
                    b.HasOne("Core.Domain.Entities.DocType", "DocType")
                        .WithMany()
                        .HasForeignKey("DocTypeSerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocType");
                });

            modelBuilder.Entity("Core.Domain.Entities.GroupMenu", b =>
                {
                    b.HasOne("Core.Domain.Entities.Group", "Group")
                        .WithMany("GroupMenus")
                        .HasForeignKey("GrpSerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MnuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Core.Domain.Entities.LoginLog", b =>
                {
                    b.HasOne("Core.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserSerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.Entities.Menu", b =>
                {
                    b.HasOne("Core.Domain.Entities.AppModule", "Module")
                        .WithMany("Menu")
                        .HasForeignKey("ModSerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Core.Domain.Entities.Reason", b =>
                {
                    b.HasOne("Core.Domain.Entities.AppModule", "Module")
                        .WithMany()
                        .HasForeignKey("ModSerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Core.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Core.Domain.Entities.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserSerialID");
                });

            modelBuilder.Entity("Core.Domain.Entities.Report", b =>
                {
                    b.HasOne("Core.Domain.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MnuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.AppModule", "Module")
                        .WithMany()
                        .HasForeignKey("ModSerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Core.Domain.Entities.User", b =>
                {
                    b.HasOne("Core.Domain.Entities.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GrpSerialID");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Domain.Entities.UserCompany", b =>
                {
                    b.HasOne("Core.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("ComSerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.User", "User")
                        .WithMany("Companies")
                        .HasForeignKey("UserSerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.Entities.UserMenuPermission", b =>
                {
                    b.HasOne("Core.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GrpSerialID");

                    b.HasOne("Core.Domain.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MnuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.User", "User")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("UserSerialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Menu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.Entities.AppModule", b =>
                {
                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Core.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Navigation("RequestSteps");
                });

            modelBuilder.Entity("Core.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Navigation("ApprovalSteps");
                });

            modelBuilder.Entity("Core.Domain.Entities.Group", b =>
                {
                    b.Navigation("GroupMenus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Core.Domain.Entities.User", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("MenuPermissions");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
